[package]
name = "driver"
version = "0.0.0"
edition = "2024"

[dependencies]
lexer = { path = "../lexer" }
parser = { path = "../parser" }

clap = { version = "4.5.41", features = ["derive"] }

[lints]
workspace = true
